// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace DemoWebCSharp {

    public partial class Regestration {

        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        protected global::System.Web.UI.WebControls.TextBox txtContact;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtDOB;
        protected global::System.Web.UI.WebControls.RadioButton rbMale;

        protected global::System.Web.UI.WebControls.RadioButton rbFemale;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        protected global::System.Web.UI.WebControls.RadioButtonList rblVaccinated;

        protected global::System.Web.UI.WebControls.Panel pnlUpload;

        protected global::System.Web.UI.WebControls.FileUpload fileCertificate;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
