<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserList.aspx.cs" Inherits="DemoWebCSharp.UserList" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>User List</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <form id="form1" runat="server">
        <div class="container mt-5">

            <h3 class="text-center mb-4 text-primary">Registered Users</h3>

            <asp:Label ID="lblWelcome" runat="server" CssClass="fw-bold text-success"></asp:Label>

            <br /><br />

            <asp:GridView ID="GridView1"
                 runat="server"
                 CssClass="table table-bordered table-striped"
                 AutoGenerateColumns="True"
                 AutoGenerateEditButton="True"
                 AutoGenerateDeleteButton="True"
                 DataKeyNames="Id"
                 OnRowEditing="GridView1_RowEditing"
                 OnRowUpdating="GridView1_RowUpdating"
                 OnRowCancelingEdit="GridView1_RowCancelingEdit"
                 OnRowDeleting="GridView1_RowDeleting"
                 OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                 AutoGenerateSelectButton="True">

                 
                
</asp:GridView>

        </div>
    </form>
</body>
</html>
